tomelilla_schools:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /app/service-account-key.json
      project: zeta-axiom-468312-f1  # Ändra detta!
      dataset: dbt_dev
      threads: 4
      timeout_seconds: 300
      location: EU
    prod:
      type: bigquery
      method: service-account
      keyfile: /app/service-account-key.json
      project: zeta-axiom-468312-f1  # Ändra detta!
      dataset: dbt_prod
      threads: 4
      timeout_seconds: 300
      location: EU