version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ai24network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - ai24network

volumes:
  data:

networks:
  ai24network:
    external: true