services:
  # Web application service
  web:
    build: .
    ports:
      - "5080:5080"
    depends_on:
      - database

  # PostgreSQL database service
  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret123
    volumes:
      # Initialize database with our SQL file
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
